services:
    laravelnuxt.api:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${OCTANE_PORT:-8000}:${OCTANE_PORT:-8000}'
            - '${PORT:-3000}:${PORT:-3000}'
        environment:
            WWWUSER: '${WWWUSER}'
            PORT: '${PORT}'
            HOST: '0.0.0.0'
            OCTANE_HOST: '0.0.0.0'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            SUPERVISOR_PHP_COMMAND: 'php artisan octane:start --watch'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on: {  }
networks:
    sail:
        driver: bridge
